### PR TITLE
SDK3 + Norwegian

### PR DESCRIPTION
**Pull request by runely**
Added **Norwegian** localization and updated app to **SDK3**

### CODE REVIEW

**Comment by ErlendVest** [comment]
Will this work on the new id lock 202 Multi? And how can I get a hold of this app? 😃

**Comment by runely** [comment]
ID Lock 202 Multi is not added as a driver in this app.

The original app is in the Homey App Store (SDK2)

To install this app you need to clone the repo and install the app via CLI

**Comment by joco73** [comment]
thanks @runely - i merged to my master. Would be great to get this out to the official app and the Homey Community.

**Comment by runely** [comment]
I have some commits coming soon. The work I did in this PR does work on already connected devices, but unfortunately not on new devices..

**Pull request merged**
